# Generated by Django 5.2.14 on 2026-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('INCOMPLETE', 'incomplete')], default='PENDING', max_length=100),
        ),
    ]
